categorylookup = {'1': 'Planets',
                  '1.1': 'Planets (Type)',
                  '1.1.1': 'Terrestrial Planets',
                  '1.1.2': 'Gas Giant Planets',
                  '1.2': 'Planets (Feature)',
                  '1.2.1': 'Planet Surfaces',
                  '1.2.1.1': 'Mountains',
                  '1.2.1.2': 'Canyons',
                  '1.2.1.3': 'Volcanic Surfaces',
                  '1.2.1.4': 'Surface Impacts',
                  '1.2.1.5': 'Surface Erosion',
                  '1.2.1.6': 'Surface Liquid',
                  '1.2.1.7': 'Surface Ice',
                  '1.2.2': 'Planetary Atmospheres',
                  '1.2.2.1': 'Atmospheric Clouds',
                  '1.2.2.2': 'Storms',
                  '1.2.2.3': 'Atmospheric Belts',
                  '1.2.2.4': 'Aurorae',
                  '1.3': 'Planets (Special Cases)',
                  '1.3.1': 'Transiting Planets',
                  '1.3.2': 'Hot Jupiters',
                  '1.3.3': 'Pulsar Planets',
                  '1.4': 'Satellites',
                  '1.4.1': 'Satellites (Feature)',
                  '1.4.1.1': 'Satellite Surfaces',
                  '1.4.1.1.1': 'Mountain',
                  '1.4.1.1.2': 'Canyon',
                  '1.4.1.1.3': 'Volcanic',
                  '1.4.1.1.4': 'Impact',
                  '1.4.1.1.5': 'Erosion',
                  '1.4.1.1.6': 'Liquid',
                  '1.4.1.1.7': 'Ice',
                  '1.4.1.2': 'Satellite Atmospheres',
                  '2': 'Interplanetary Bodies',
                  '2.1': 'Dwarf Planets',
                  '2.2': 'Comets',
                  '2.2.1': 'Comet Nuclei',
                  '2.2.2': 'Comet Coma',
                  '2.2.3': 'Comet Tails',
                  '2.2.3.1': 'Comets (Dust)',
                  '2.2.3.2': 'Comets (Gas)',
                  '2.3': 'Asteroids',
                  '2.4': 'Meteoroids',
                  '3': 'Stars',
                  '3.1': 'Stars (Evolutionary Stage)',
                  '3.1.1': 'Protostar',
                  '3.1.2': 'Young Stellar Object',
                  '3.1.3': 'Main Sequence Star',
                  '3.1.4': 'Red Giants',
                  '3.1.5': 'Red Supergiants',
                  '3.1.6': 'Blue Supergiants',
                  '3.1.7': 'White Dwarf Stars',
                  '3.1.8': 'Supernovae',
                  '3.1.9': 'Neutron Stars',
                  '3.1.9.1': 'Pulsars',
                  '3.1.9.2': 'Magnetars',
                  '3.1.10': 'Black Holes',
                  '3.2': 'Stars (Type)',
                  '3.2.1': 'Variable Stars',
                  '3.2.1.1': 'Pulsating Stars',
                  '3.2.1.2': 'Irregular Stars',
                  '3.2.1.3': 'Eclipsing Stars',
                  '3.2.1.4': 'Flare Stars',
                  '3.2.1.5': 'Novae',
                  '3.2.1.6': 'X-Ray Binaries (Star)',
                  '3.3': 'Stars with Spectral Types',
                  '3.3.1': 'O Stars',
                  '3.3.2': 'B Stars',
                  '3.3.3': 'A Stars',
                  '3.3.4': 'F Stars',
                  '3.3.5': 'G Stars',
                  '3.3.6': 'K Stars',
                  '3.3.7': 'M Stars',
                  '3.3.8': 'L Stars',
                  '3.3.9': 'T Stars',
                  '3.4': 'Stellar Populations',
                  '3.4.1': 'Population I Stars',
                  '3.4.2': 'Population II Stars',
                  '3.4.3': 'Population III Stars',
                  '3.5': 'Stellar feature',
                  '3.5.1': 'Photosphere',
                  '3.5.1.1': 'Granulation',
                  '3.5.1.2': 'Sunspot',
                  '3.5.2': 'Chromosphere',
                  '3.5.2.1': 'Flare',
                  '3.5.2.2': 'Facula',
                  '3.5.3': 'Corona',
                  '3.5.3.1': 'Prominence',
                  '3.6': 'Group of Stars',
                  '3.6.1': 'Binary Stars',
                  '3.6.2': 'Triple Stars',
                  '3.6.3': 'Multiple Stars',
                  '3.6.4': 'Clusters of Stars',
                  '3.6.4.1': 'Open Clusters',
                  '3.6.4.2': 'Globular Clusters',
                  '3.7': 'Circumstellar Material',
                  '3.7.1': 'Planetary Systems',
                  '3.7.2': 'Disks',
                  '3.7.2.1': 'Protoplanetary Disks',
                  '3.7.2.2': 'Accretion Disks',
                  '3.7.2.3': 'Debris Disks',
                  '3.7.3': 'Outflows',
                  '3.7.3.1': 'Solar Winds',
                  '3.7.3.2': 'Coronal Mass Ejection',
                  '4': 'Nebulae',
                  '4.1': 'Nebulae (Type)',
                  '4.1.1': 'Interstellar Medium',
                  '4.1.2': 'Star Formation',
                  '4.1.3': 'Planetary Nebulae',
                  '4.1.4': 'Supernova Remnants',
                  '4.1.5': 'Jets',
                  '4.2': 'Nebulae (Appearance)',
                  '4.2.1': 'Emission Nebulae',
                  '4.2.1.1': 'H II Regions',
                  '4.2.2': 'Reflection Nebulae',
                  '4.2.2.1': 'Light Echo',
                  '4.2.3': 'Dark Nebulae',
                  '4.2.3.1': 'Molecular Clouds',
                  '4.2.3.2': 'Bok Globules',
                  '4.2.3.3': 'Proplyds',
                  '5': 'Galaxies',
                  '5.1': 'Galaxies (Type)',
                  '5.1.1': 'Spiral Galaxies',
                  '5.1.2': 'Barred Galaxies',
                  '5.1.3': 'Lenticular Galaxies',
                  '5.1.4': 'Elliptical Galaxies',
                  '5.1.5': 'Ring Galaxies',
                  '5.1.6': 'Irregular Galaxies',
                  '5.1.7': 'Interacting Galaxies',
                  '5.2': 'Galaxies (Size)',
                  '5.2.1': 'Giant Galaxies',
                  '5.2.2': 'Dwarf Galaxies',
                  '5.3': 'Galaxies (Activity)',
                  '5.3.1': 'Galaxies with normal activity',
                  '5.3.2': 'AGN',
                  '5.3.2.1': 'Quasars',
                  '5.3.2.2': 'Seyfert Galaxies',
                  '5.3.2.3': 'Blazars',
                  '5.3.2.4': 'Liner Galaxies',
                  '5.3.3': 'Starburst Galaxies',
                  '5.3.4': 'Ultraluminous Galaxies',
                  '5.4': 'Galaxies (Component)',
                  '5.4.1': 'Bulges',
                  '5.4.2': 'Bars',
                  '5.4.3': 'Disks',
                  '5.4.4': 'Halos',
                  '5.4.5': 'Rings',
                  '5.4.6': 'Central Black Holes',
                  '5.4.7': 'Spiral Arms',
                  '5.4.8': 'Dust Lanes',
                  '5.4.9': 'Center Cores',
                  '5.5': 'Galaxies (Grouping)',
                  '5.5.1': 'Pair of Galaxies',
                  '5.5.2': 'Multiple Galaxies',
                  '5.5.3': 'Galaxy Clusters',
                  '5.5.4': 'Galaxy Superclusters',
                  '6': 'Cosmology',
                  '6.1': 'Cosmology (Morphology)',
                  '6.1.1': 'Deep Field',
                  '6.1.2': 'Large-scale Structure',
                  '6.1.3': 'Cosmic Background',
                  '6.2': 'Cosmology (Phenomenon)',
                  '6.2.2': 'Gamma Ray Burst',
                  '6.2.3': 'Dark Matter',
                  '7': 'Sky Phenomenon',
                  '7.1': 'Night Sky',
                  '7.1.1': 'Constellations',
                  '7.1.2': 'Asterisms',
                  '7.1.3': 'Milky Way',
                  '7.1.4': 'Trails',
                  '7.1.4.1': 'Meteor Trails',
                  '7.1.4.2': 'Star Trails',
                  '7.1.4.3': 'Satellite Trails',
                  '7.1.5': 'Zodiacal Light',
                  '7.1.5.1': 'Gegenschein',
                  '7.1.5.2': 'Night glow',
                  }
categories = [
    {'link': "planets", 'name': 'Planets', 'avm': 1},
    {'link': "interplanetarybodies",
        'name': 'Interplanetary Bodies', 'avm': 2},
    {'link': "stars", 'name': 'Stars', 'avm': 3},
    {'link': "nebulae", 'name': 'Nebulae', 'avm': 4},
    {'link': "galaxies", 'name': 'Galaxies', 'avm': 5},
    {'link': "cosmology", 'name': 'Cosmology', 'avm': 6},
    {'link': "sky", 'name': 'Sky Phenomenon', 'avm': 7}]
